services:
  is-my-burguer-pedido:
    container_name: is-my-burguer-pedido
    image: docker.io/ismaelgcosta/is-my-burguer-pedido:is-my-burguer-pedido-2.1.1
    environment:
      - AWS_REGION
      - CLIENT_DOMAIN
      - AWS_COGNITO_USER_POOL_ID
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - SERVICE_DISCOVERY_USERNAME
      - SERVICE_DISCOVERY_PASSWORD
    build:
        dockerfile: Dockerfile
    ports:
      - '127.0.0.1:8943:8943'
    restart: unless-stopped
    networks:
      - ismyburguer-backend

networks:
  ismyburguer-backend:
    external: false
    driver: bridge